name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GODOT_VERSION: 4.6.2
  ITCH_USERNAME: cats-paw
  ITCH_GAME_ID: machine-jam
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.6.2
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build Godot Project
        run: |
          mkdir -p build
          godot --headless --export-release Web build/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Deploy to itch.io
        uses: KikimoraGames/itch-publish@v0.0.3
        with:

          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
          buildChannel: web

